#!/usr/bin/env bash

script_dir=$(realpath "$(dirname "$0")")
main_dir="${script_dir}/.."

GREEN=$(printf '\033[0;32m')
ENDMARK=$(printf '\033[m')

# Note that you need to run it in the directory where the test script is located.
for test_folder in test_*/; do
    if [ ! -d "$test_folder" ]; then
        echo "Skipping non-directory: $test_folder"
        continue
    fi

    echo "=============== Running $test_folder ... ==============="
    # get the target precessor architecture.
    # remove the trailing /.
    test_folder=${test_folder%/}
    arch=${test_folder#test_}
    if [[ "$arch" = "" ]]; then
        echo "$GREEN""$test_folder is invalid, should be test_<arch_name>, skip.""$ENDMARK"
        continuegit stat
    fi

    echo "running sub-test for $arch"
    python3 "$main_dir"/__main__.py --output-format json --output "./$test_folder/$arch.json" --arch "$arch" ./"$test_folder"
    if [[ $? -eq 0 ]]; then
        echo "running scanner diff"
        python3 "$script_dir"/scanner_diff.py --src-dir "./$test_folder/" --json-report "./$test_folder/$arch.json" --test-dir "$test_folder"
    fi
done
