#!/usr/bin/env bash

script_dir=$(realpath "$(dirname "$0")")
main_dir="${script_dir}/.."

GREEN=$(printf '\033[0;32m')
ENDMARK=$(printf '\033[m')

# Note that you need to run it in the directory where the test script is located.
test_folders="$*"
[[ "$test_folders" = "" ]] && test_folders=$(find -L . -type d -name 'test_*')

for c in $test_folders ; do
    echo "=============== Running cases in $c ... ==============="
    cd "$script_dir"/"$c" || { echo "Failure"; exit 1; }

    if [[ -e "disabled" ]]; then
        echo "$GREEN""$c is disabled, skip.""$ENDMARK"
        continue
    fi

    #Currently the test cases in docker module are only for aarch64 architecture.
    arch="aarch64"
    if [ ! -d "./aarch64" ]; then
        echo "$GREEN""$c/$arch is empty, skip.""$ENDMARK"
        continue
    fi

    echo "running sub-test for $arch"
    python3 "$main_dir"/__main__.py --output-format json --output "./$arch/$arch.json" --arch "$arch" ./"$arch"
    if [[ $? -eq 0 ]]; then
        echo "running scanner diff"
        python3 "$script_dir"/scanner_diff.py --src-dir "./$arch/" --json-report "./$arch/$arch.json" --test-dir "$c"
    fi
done
